# Generated by Django 4.2.2 on 2023-06-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_generaladditionalinfo_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_coach_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
