# Generated by Django 4.2.2 on 2023-06-28 14:00

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_coach_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
