# Generated by Django 4.2.2 on 2023-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_motivation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='description',
            field=models.TextField(),
        ),
    ]
