# Generated by Django 4.2.2 on 2023-07-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_motivation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaladditionalinfo',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_pictures'),
            preserve_default=False,
        ),
    ]
