# Generated by Django 4.2.2 on 2023-07-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_generaladditionalinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaladditionalinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
