# Generated by Django 4.2.2 on 2023-07-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='station',
        ),
    ]
