# Generated by Django 4.2.2 on 2023-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='was_meeting_attended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
