# Generated by Django 4.2.2 on 2023-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_was_meeting_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='was_meeting_attended',
            field=models.BooleanField(null=True),
        ),
    ]
