# Generated by Django 4.2.2 on 2023-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_remove_meeting_requested_has_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='was_meeting_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
