# Generated by Django 4.2.2 on 2023-07-31 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_alter_meeting_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
