# Generated by Django 4.2.2 on 2023-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_rename_time_meeting_end_time_meeting_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='was_meeting_cancelled',
            field=models.BooleanField(null=True),
        ),
    ]
