# Generated by Django 4.2.2 on 2023-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_meeting_was_meeting_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='was_meeting_rejected',
            field=models.BooleanField(null=True),
        ),
    ]
