# Generated by Django 4.2.2 on 2023-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
