# Generated by Django 4.2.2 on 2023-10-16 07:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('review_ratings', '0003_offerreviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerreviewrating',
            name='review',
            field=tinymce.models.HTMLField(),
        ),
    ]
